services:
  backend:
    build: ./apps/backend
    depends_on:
      - redis
    env_file:
      - apps/backend/.env
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
  
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
